
import { Quote } from '../types';

export const HAPPY_QUOTES: Quote[] = [
  { text: "Ton éclat est contagieux, Lydie, continue de briller comme une étoile ! ✨" },
  { text: "Le bonheur te va si bien, Lydie, profite de chaque seconde de cette belle énergie." },
  { text: "Tu es capable d'accomplir des choses incroyables quand tu as ce sourire, Lydie." },
  { text: "Aujourd'hui est une magnifique journée pour que tu conquières le monde, Lydie !" },
  { text: "Ta joie est ta super-puissance, Lydie. Utilise-la pour inspirer les autres." },
  { text: "Continue sur cette lancée, Lydie, rien ne peut t'arrêter quand tu es si rayonnante." },
  { text: "Le succès suit naturellement une femme comme toi, Lydie, qui garde un cœur joyeux." },
  { text: "Tu es une source de lumière infinie pour tous ceux qui t'entourent, Lydie." },
  { text: "Chaque rire de ta part, Lydie, est un pas de plus vers tes rêves les plus fous." },
  { text: "Ta positivité, Lydie, crée des opportunités là où les autres ne voient que des obstacles." },
  { text: "N'oublie jamais, Lydie, que tu es la seule et unique créatrice de ton propre bonheur." },
  { text: "Lydie, le monde a cruellement besoin de ta vitalité et de ton enthousiasme unique." },
  { text: "Fais confiance à ton instinct, Lydie, il t'emmène vers des sommets inexplorés." },
  { text: "Ta réussite d'aujourd'hui, Lydie, n'est que le début d'une aventure encore plus épique." },
  { text: "Brille si fort aujourd'hui, Lydie, que le soleil lui-même en sera jaloux !" },
  { text: "Lydie, ton enthousiasme est une flamme qui réchauffe tous les cœurs. 🔥" },
  { text: "La vie te sourit parce que tu lui souris en retour, Lydie." },
  { text: "Rien n'est trop grand pour ton ambition aujourd'hui, Lydie !" },
  { text: "Lydie, tu es une édition limitée de pur bonheur." },
  { text: "Ton énergie positive est ton meilleur accessoire aujourd'hui, Lydie." },
  { text: "Lydie, savoure cette victoire, tu l'as amplement méritée." },
  { text: "Le monde est ton terrain de jeu aujourd'hui, Lydie, amuse-toi !" },
  { text: "Ta confiance en toi est ton plus beau vêtement, Lydie." },
  { text: "Lydie, chaque battement de ton cœur est une note de joie." },
  { text: "Tu transformes l'ordinaire en extraordinaire par ta simple présence, Lydie." },
  { text: "Lydie, rayonne comme si personne ne te regardait." },
  { text: "La chance t'accompagne car tu l'attires par ta joie, Lydie." },
  { text: "Lydie, ton sourire est le plus court chemin entre deux cœurs." },
  { text: "Aujourd' oser tout te semble facile, et tu as raison, Lydie !" },
  { text: "Lydie, tu es un aimant à bonnes nouvelles aujourd'hui." },
  { text: "Ton optimisme est une force invincible, Lydie." },
  { text: "Lydie, ne t'arrête jamais de rêver en grand, tu es faite pour ça." },
  { text: "Le bonheur est un voyage, et tu es la meilleure guide, Lydie." },
  { text: "Lydie, ta lumière intérieure éclaire même les recoins les plus sombres." },
  { text: "Quelle belle journée pour être une femme aussi géniale que toi, Lydie !" },
  { text: "Lydie, ton courage et ta joie forment un duo imbattable." },
  { text: "Tu es la capitaine de ton propre bonheur, Lydie, et tu navigues à merveille." },
  { text: "Lydie, aujourd'hui, tout te réussit car tu y crois de tout ton cœur." },
  { text: "Ton rire est la musique préférée de tes amis, Lydie." },
  { text: "Lydie, garde cette étincelle, c'est elle qui fait ta magie." },
  { text: "Tu es une source d'inspiration pour nous tous, Lydie." },
  { text: "Lydie, aujourd'hui est le jour idéal pour célébrer qui tu es." },
  { text: "Ta vitalité est une bouffée d'oxygène pour ton entourage, Lydie." },
  { text: "Lydie, fonce, le monde n'attend que ton talent." },
  { text: "Rien ne peut ternir ton éclat aujourd'hui, Lydie." },
  { text: "Lydie, tu es la preuve que la gentillesse et le succès vont de pair." },
  { text: "Ton cœur est un jardin de bonheur que tu partages généreusement, Lydie." },
  { text: "Lydie, chaque moment de joie aujourd'hui sera un souvenir précieux demain." },
  { text: "Tu es une guerrière de la lumière, Lydie, continue de gagner !" },
  { text: "Lydie, profite de cette journée, elle est faite sur mesure pour toi. ✨" }
];



export const NEUTRAL_QUOTES: Quote[] = [
  { text: "Chaque petit pas compte, Lydie. Tu avances à ton rythme, et c'est absolument parfait. 🌸" },
  { text: "Prends un moment pour respirer, Lydie. Tu es exactement là où tu dois être." },
  { text: "La douceur envers toi-même est ta clé pour une journée réussie, Lydie." },
  { text: "Aujourd'hui, Lydie, choisis d'être simplement présente et infiniment gentille avec toi." },
  { text: "Même les jours tranquilles cachent de petites pépites de bonheur pour toi, Lydie." },
  { text: "Tu n'as pas besoin de courir, Lydie, pour arriver à bon port en toute sérénité." },
  { text: "Lydie, une fleur ne se compare pas aux autres, elle fleurit simplement. Fais de même." },
  { text: "Ton calme est une force tranquille qui te mènera exactement là où tu veux, Lydie." },
  { text: "Savoure ce moment de paix mérité, Lydie, tu es une personne exceptionnelle." },
  { text: "Le plus important, Lydie, n'est pas d'aller vite, mais de ne jamais cesser d'avancer." },
  { text: "Sois patiente avec toi-même, Lydie, les plus belles choses prennent du temps à mûrir." },
  { text: "Lydie, une tasse de thé, un bon moment de calme et ton propre sourire suffisent amplement." },
  { text: "La vie est faite de nuances délicates, Lydie, profite de la douceur de cet instant." },
  { text: "Fais de ton mieux avec ce que tu as aujourd'hui, Lydie, et sache que c'est déjà immense." },
  { text: "Tu es une personne précieuse et irremplaçable, Lydie, même dans tes moments de repos." },
  { text: "Lydie, le silence est parfois la plus belle des mélodies. Écoute-le. 🌿" },
  { text: "La paix commence par un sourire intérieur, Lydie." },
  { text: "Lydie, accorde-toi le luxe de ne rien faire pendant quelques minutes." },
  { text: "Aujourd'hui, Lydie, cultive ton jardin intérieur avec patience." },
  { text: "Lydie, la simplicité est la sophistication suprême de l'âme." },
  { text: "Prends le temps d'observer le ciel, Lydie, il a tant à t'apprendre sur l'espace." },
  { text: "Lydie, ton calme est ton super-pouvoir dans ce monde agité." },
  { text: "Chaque respiration est une opportunité de recommencer à zéro, Lydie." },
  { text: "Lydie, sois ton propre havre de paix aujourd'hui." },
  { text: "Rien ne presse, Lydie, la vie se déguste par petits morceaux." },
  { text: "Lydie, la sérénité n'est pas l'absence d'orage, mais le calme au centre." },
  { text: "Fais confiance au timing de ta vie, Lydie, tout arrive au bon moment." },
  { text: "Lydie, une journée paisible est une journée réussie." },
  { text: "Écoute ton intuition, Lydie, elle connaît le chemin de la tranquillité." },
  { text: "Lydie, sois douce avec tes pensées comme tu le serais avec une amie." },
  { text: "Le bonheur se trouve souvent dans les choses simples, Lydie." },
  { text: "Lydie, autorise-toi à ralentir pour mieux apprécier le paysage." },
  { text: "Ta présence tranquille est un cadeau pour ton entourage, Lydie." },
  { text: "Lydie, la vie est un équilibre entre tenir bon et lâcher prise." },
  { text: "Aujourd'hui, Lydie, contente-toi d'être, c'est déjà beaucoup." },
  { text: "Lydie, chaque instant est un nouveau départ." },
  { text: "La clarté vient de l'esprit calme, Lydie." },
  { text: "Lydie, savoure le silence, il contient toutes les réponses." },
  { text: "Ton harmonie intérieure est ta plus grande richesse, Lydie." },
  { text: "Lydie, regarde autour de toi et trouve trois petites choses pour lesquelles remercier." },
  { text: "La patience est une fleur qui finit toujours par éclore, Lydie." },
  { text: "Lydie, laisse les événements couler comme de l'eau sur une pierre." },
  { text: "Aujourd'hui, Lydie, protège ta paix intérieure comme un trésor." },
  { text: "Lydie, tu as le droit de dire non pour préserver ton équilibre." },
  { text: "La vie est plus belle quand on prend le temps de la regarder, Lydie." },
  { text: "Lydie, ton énergie est précieuse, utilise-la avec sagesse." },
  { text: "Sois reconnaissante pour ce que tu as en attendant ce qui arrive, Lydie." },
  { text: "Lydie, la douceur est une force que peu de gens maîtrisent aussi bien que toi." },
  { text: "Trouve la beauté dans l'imperfection d'aujourd'hui, Lydie." },
  { text: "Lydie, respire, souris et continue simplement ton chemin. 🌸" }
];

export const SAD_QUOTES: Quote[] = [
  { text: "C'est ok de ne pas être au top aujourd'hui, Lydie. Demain est une nouvelle chance. 💖" },
  { text: "Les nuages ne font que passer, Lydie, mais ton soleil intérieur reste là, juste derrière." },
  { text: "Ta force ne se mesure pas à tes larmes, Lydie, mais à ton immense courage de continuer." },
  { text: "Lydie, même après la pluie la plus sombre, ton arc-en-ciel finira par apparaître." },
  { text: "Prends soin de toi, Lydie, avec la même tendresse que tu aurais pour un petit chaton." },
  { text: "Cette tristesse est temporaire, Lydie, mais ta lumière, elle, est éternelle." },
  { text: "Sois ton propre refuge aujourd'hui, Lydie. Sois douce, patiente et aimante avec toi." },
  { text: "Lydie, il n'y a pas d'échec, seulement des leçons précieuses pour ton grand voyage." },
  { text: "Tu es beaucoup plus forte et résiliente que ce que tu imagines en ce moment, Lydie." },
  { text: "Le repos n'est pas de la paresse, Lydie, c'est une nécessité vitale pour ton grand cœur." },
  { text: "Même dans l'obscurité la plus totale, Lydie, tu as le pouvoir de trouver une étincelle." },
  { text: "Lydie, ne compare jamais ton chapitre difficile au film parfait que les autres affichent." },
  { text: "Chaque larme libère un peu du poids que ton âme n'a plus à porter seule, Lydie." },
  { text: "On ne peut voir la beauté des étoiles que lorsqu'il fait vraiment nuit, Lydie." },
  { text: "Demain, Lydie, tu te sentiras un peu plus légère. Accroche-toi, tu es infiniment aimée." },
  { text: "Lydie, autorise-toi à pleurer si besoin, l'eau nettoie l'âme. 🌧️" },
  { text: "Ta vulnérabilité est une forme de courage, Lydie." },
  { text: "Lydie, le tunnel a toujours une sortie, même si tu ne la vois pas encore." },
  { text: "Ne sois pas si dure avec toi-même, Lydie, tu fais de ton mieux." },
  { text: "Lydie, même les jours gris font partie du paysage de la vie." },
  { text: "Accueille ta peine comme une amie de passage, Lydie, elle ne restera pas." },
  { text: "Lydie, ton cœur a besoin de repos, écoute-le sans culpabiliser." },
  { text: "Les étoiles brillent plus fort quand la nuit est noire, Lydie." },
  { text: "Lydie, chaque épreuve est un engrais pour ta future floraison." },
  { text: "Il n'y a pas de honte à avoir besoin d'aide, Lydie, nous sommes là." },
  { text: "Lydie, respire doucement, une minute à la fois." },
  { text: "Même les guerrières comme toi ont besoin de poser leur armure, Lydie." },
  { text: "Lydie, la douleur est une enseignante sévère, mais elle passera." },
  { text: "Garde espoir, Lydie, le soleil finit toujours par se lever." },
  { text: "Lydie, tu es entourée d'amour, même quand tu te sens seule." },
  { text: "Ta résilience est ton héritage le plus précieux, Lydie." },
  { text: "Lydie, fais un petit pas aujourd'hui, c'est suffisant." },
  { text: "La tristesse n'est qu'un nuage qui cache temporairement ta beauté, Lydie." },
  { text: "Lydie, rappelle-toi les tempêtes que tu as déjà traversées avec succès." },
  { text: "Ta valeur n'est pas liée à ton humeur du jour, Lydie." },
  { text: "Lydie, sois gentille avec ton cœur blessé." },
  { text: "Même brisée, une lumière peut encore éclairer, Lydie." },
  { text: "Lydie, accorde-toi le temps nécessaire pour guérir." },
  { text: "Le changement est la seule constante, Lydie, cela aussi passera." },
  { text: "Lydie, tu es un diamant : plus on te presse, plus tu deviens forte." },
  { text: "Prends un plaid, un thé et laisse le monde tourner sans toi un instant, Lydie." },
  { text: "Lydie, tes émotions sont valides, ne les étouffe pas." },
  { text: "L'espoir est la petite voix qui chuchote 'essaie encore' demain, Lydie." },
  { text: "Lydie, tu as le droit de ne pas être forte tout le temps." },
  { text: "Regarde le ciel, Lydie, il est vaste assez pour contenir tous tes soucis." },
  { text: "Lydie, tu es plus aimée que tu ne le penses." },
  { text: "La douceur est le meilleur remède pour ton âme fatiguée, Lydie." },
  { text: "Lydie, fais confiance à la vie, elle te prépare des jours meilleurs." },
  { text: "Chaque fin est le début de quelque chose de nouveau, Lydie." },
  { text: "Lydie, accroche-toi à la petite étincelle au fond de toi. 💖" },
  { text: "Si t'es mal, ben juste force à toi." }
];